---
github_user: pddg
ghq_root: '{{ lookup("env","HOME") }}/ghq'
repos_root: '{{ ghq_root }}/github.com/{{ github_user }}'
dotfiles_repo: '{{ repos_root }}/dotfiles'

anyenv_plugins:
  - repo: "https://github.com/znz/anyenv-update"
  - repo: "https://github.com/amashigeseiji/anyenv-lazyload"
anyenv_envs:
  - pyenv
  - nodenv

pyenv_install_versions:
  - 3.8.4
  - 2.7.17
pyenv_virtualenvs:
  - name: neovim3
    version: 3.8.4
    modules:
      - pynvim
  - name: neovim2
    version: 2.7.17
    modules:
      - pynvim
