---
- name: Obtain path to openssl (workaround for High Sierra)
  shell: brew --prefix openssl
  register: openssl_prefix
  changed_when: false
  check_mode: no
  run_once: yes

- name: Obtain path to sdk
  shell: xcrun --show-sdk-path
  register: xcrun_sdk_path
  changed_when: false
  check_mode: no

- block:
  - name: "{{ item }}: Install python interpreters"
    shell: "pyenv install {{ item }}"
    args:
      creates: '{{ pyenv_install_dir }}/versions/{{ item }}'
    environment:
      PATH: "{{ pyenv_install_dir }}/bin:{{ ansible_env.PATH }}"
      PYENV_ROOT: "{{ pyenv_install_dir }}"
      CFLAGS: '-I{{ openssl_prefix.stdout }}/include'
      LDFLAGS: '-L{{ openssl_prefix.stdout }}/lib -L{{ xcrun_sdk_path.stdout }}/usr/lib'
    notify:
      - Pyenv rehash

  rescue:
    - name: "{{ item }}: Delete failed version directory"
      file:
        state: absent
        path: '{{ pyenv_install_dir }}/versions/{{ item }}'
