---
# Refs: https://github.com/pyenv/pyenv/wiki#suggested-build-environment
- name: Install dependencies (darwin)
  homebrew:
    name:
      - openssl
      - readline
      - sqlite3
      - xz
      - zlib
