---
- block:
  - name: "{{ item }}: Install"
    shell: "pyenv install {{ item }}"
    args:
      creates: '{{ pyenv_install_dir }}/versions/{{ item }}'
    environment:
      PATH: "{{ pyenv_install_dir }}/bin:{{ ansible_env.PATH }}"
      PYENV_ROOT: "{{ pyenv_install_dir }}"
    notify:
      - Pyenv rehash

  rescue:
    - name: "{{ item }}: Delete failed version directory"
      file:
        state: absent
        path: '{{ pyenv_install_dir }}/versions/{{ item }}'
