- include_tasks: brew.yml
  when: ansible_os_family == 'Darwin'

- include_tasks: apt.yml
  when: ansible_os_family == 'Debian'

- name: Obtain path to fish
  shell: which fish
  register: fish_path
  changed_when: false
  check_mode: no

- name: Add fish shell to /etc/shells
  lineinfile:
    dest: /etc/shells
    line: '{{ fish_path.stdout }}'
  become: yes

- name: Setup user shell
  user:
    name: '{{ lookup("env", "USER") }}'
    shell: '{{ fish_path.stdout }}'
    system: yes
  become: yes

- name: Obtain path to fish
  shell: which fish
  register: fish_path
  changed_when: false
  check_mode: no

- name: Set ansible_shell_executable to fish
  set_fact:
    ansible_shell_executable: '{{ fish_path.stdout }}'
    ansible_shell_type: fish

- name: Create fish config dir
  file:
    path: ~/.config/fish
    state: directory

- name: Create functions dir
  file:
    path: ~/.config/fish/functions
    state: directory

- name: Install fisherman
  get_url:
    url: https://git.io/fisher
    dest: ~/.config/fish/functions/fisher.fish
  register: download_result
  until: download_result is succeeded
  retries: 3
  delay: 5

- name: Put config files
  file:
    src: '{{ dotfiles_repo }}/{{ item }}'
    dest: ~/{{ item }}
    state: link
    force: yes
  with_items:
    - '{{ fish_config_files }}'

- name: Install fish plugins
  shell: fisher
  changed_when: false
