version: 2
updates:
  - package-ecosystem: "pip"
    directory: '/roles/pddg.anyenv'
    schedule:
      interval: 'monthly'
    ignore:
      - dependency-name: '*'
  - package-ecosystem: "pip"
    directory: '/roles/pddg.pyenv'
    ignore:
      - dependency-name: '*'
    schedule:
      interval: 'monthly'
  - package-ecosystem: "pip"
    directory: '/roles/pddg.ghq'
    ignore:
      - dependency-name: '*'
    schedule:
      interval: 'monthly'