version: 2
updates:
  - package-ecosystem: "pip"
    directory: '/roles/pddg.anyenv'
    ignore: '*'
  - package-ecosystem: "pip"
    directory: '/roles/pddg.pyenv'
    ignore: '*'
  - package-ecosystem: "pip"
    directory: '/roles/pddg.ghq'
    ignore: '*'