language: python

matrix:
  include:
    - os: linux
      dist: xenial
      python: 3.6

cache: 'pip'

before_install:
  - pip install ansible ansible-lint

script:
  - ansible-lint playbooks/*
  - for f in playbooks/* ; do ansible-playbook $f --syntax-check; done

