- name: dotfiles repository is pulled
  git:
    repo: https://github.com/pddg/dotfiles
    dest: '{{ dotfiles_repo }}'
    update: yes

- name: actual dotfiles are linked into dotfiles repository
  file:
    src: '{{ dotfiles_repo }}/{{ item }}'
    dest: ~/{{ item }}
    state: link
    force: yes
  loop: '{{ dotfiles_list }}'
