- name: git clone dotfiles
  git:
    repo: https://github.com/pddg/dotfiles
    dest: '{{ dotfiles_repo }}'
    update: no

- name: Create symbolic link
  file:
    src: '{{ dotfiles_repo }}/{{ item }}'
    dest: ~/{{ item }}
    state: link
    force: yes
  with_items:
    - '{{ dotfiles_list }}'

