- block:
  - name: Install font
    copy:
      src: '{{ item.src }}'
      dest: ~/Library/Fonts
    when: '".otf" in item.path or ".ttf" in item.path'
    with_filetree:
      - "{{ font_dir }}/"

  tags: font_install
