- block:
  - name: Create font dir
    file:
      path: "{{ font_dir }}"
      state: directory

  - name: Download font
    get_url:
      url: '{{ item.url }}'
      dest: '~/Documents/fonts/{{ item.name }}'
    register: download_result
    until: download_result is succeeded
    retries: 3
    delay: 5
    with_items:
      - '{{ font_list }}'

  - name: Unzip archive
    unarchive:
      src: '{{ item }}'
      dest: '{{ font_dir }}/'
      remote_src: yes
    with_fileglob:
      - "{{ font_dir }}/*.zip"

  tags: font_download

- include_tasks: macos.yml
  when: ansible_os_family == 'Darwin'

- include_tasks: ubuntu.yml
  when: ansible_os_family == 'Debian'
