homebrew_taps:
  - { name: caskroom/cask }
  - { name: caskroom/versions }
  - { name: homebrew/bundle }
  - { name: homebrew/core }
  - { name: neovim/neovim }

homebrew_packages:
  - { name: ansible }
  - { name: ghq }
  - { name: git }
  - { name: ghostscript }
  - { name: go }
  - { name: fish }
  - { name: hugo }
  - { name: libxml2 }
  - { name: libpng }
  - { name: libjpeg }
  - { name: libusb }
  - { name: openssl }
  - { name: nmap }
  - { name: pcre }
  - { name: peco }
  - { name: wget }

homebrew_cask_packages:
  # browser
  - { name: firefox }
  - { name: google-chrome }
  - { name: vivaldi-snapshot }
  # development tools
  - { name: mysqlworkbench }
  - { name: iterm2 }
  - { name: pycharm }
  - { name: webstorm }
  - { name: goland }
  - { name: clion }
  - { name: gitkraken }
  - { name: visual-studio-code }
  - { name: typora }
  - { name: vagrant }
  - { name: docker }
  # Communication tools
  - { name: slack }
  - { name: skype }
  # other utils
  - { name: appcleaner }
  - { name: licecap }
  - { name: karabiner-elements }
  - { name: alfred }
  - { name: macpass }
  - { name: moom }
  - { name: dropbox }
  - { name: evernote }
  - { name: mendeley }
  - { name: google-backup-and-sync }
  - { name: xquartz }
  - { name: chromedriver }
