- name: brew update
  homebrew:
    update_homebrew: yes

- name: additional fomulas are tapped
  homebrew_tap:
    name: '{{ item.name }}'
    state: present
  with_items:
    - '{{ homebrew_taps }}'

- name: packages are installed by homebrew
  homebrew:
    name: '{{ homebrew_packages }}'
  with_items:

- name: desktop apps are installed by homebrew
  homebrew_cask:
    name: '{{ homebrew_cask_packages }}'
    accept_external_apps: True
