nvim_python2_version: 2.7.14
nvim_python3_version: 3.6.2
nvim_module_version: 0.2.6
nvim_config_files:
  - .config/nvim/init.vim
  - .config/nvim/dein.toml
  - .config/nvim/dein_lazy.toml
ubuntu_nvim_depends:
  - cmake
  - libboost-all-dev
  - libicu-dev
  - neovim
macos_nvim_depends:
  - cmake
  - boost
  - neovim
