- name: Set ansible_shell_type to fish
  set_fact:
    ansible_shell_type: fish
    ansible_shell_executable: /usr/local/bin/fish

- name: Place anyenv repository
  git:
    repo: https://github.com/riywo/anyenv.git
    dest: ~/.anyenv

- name: Add init script of anyenv to config.fish
  lineinfile:
    dest: ~/.config/fish/config.fish
    line: "{{ item }}"
  with_items:
    - set -x PATH $HOME/.anyenv/bin $PATH
    - eval (anyenv init - fish)

- name: Install pyenv
  shell: anyenv install pyenv
  args:
    creates: ~/.ansible/env/pyenv/bin/pyenv

  #- name: Add init script of pyenv to config.fish
  #lineinfile:
    #dest: ~/.config/fish/config.fish
    #    line: '{{ item }}'
- name: Install python
  shell: pyenv install '{{ item }}'
  args:
    creates: ~/.anyenv/envs/pyenv/versions/{{ version }}
  with_items:
    - '{{ python_versions }}'
  when: python_versions is defined
  notify:
    - pyenv_rehash




