- block:
  - name: Install goenv
    shell: anyenv install goenv
    args:
      creates: ~/.anyenv/envs/goenv/bin/goenv

  tags: goenv_install

- block:
  - name: Install go
    shell: goenv install '{{ item.version }}'
    args:
      creates: '~/.anyenv/envs/goenv/versions/{{ item.version }}'
    with_items:
      - '{{ go_versions }}'
    when: go_versions is defined
    notify:
      - goenv_rehash

  tags: go_install
