---
- hosts: local
  connection: local
  roles:
    - name: font
      tags: font

    - name: git
      tags: git

    - name: apt
      when: 'ansible_os_family == "Debian"'
      tags: apt

    - name: brew
      when: 'ansible_os_family == "Darwin"'
      tags: brew

    - name: dotfiles
      tags: dotfiles

    - name: macos
      when: 'ansible_os_family == "Darwin"'
      tags: macos

    - name: pddg.ghq
      tags: ghq
      vars:
        ghq_version: 1.1.7

    - name: pddg.anyenv
      tags: anyenv

    - name: pddg.pyenv
      tags: pyenv

    - name: nvim
      tags: nvim
