---
- hosts: local
  connection: local
  roles:
    - name: pddg.ghq
      tags: ghq
      vars:
        ghq_version: 1.1.7

    - name: pddg.anyenv
      tags: anyenv

    - name: pddg.pyenv
      tags: pyenv

    - name: nvim
      tags: nvim
