- name: Add apt repositories
  apt_repository:
    repo: ppa:neovim-ppa/unstable
    update_cache: yes
  become: yes

- name: Install neovim by apt
  apt:
    name: '{{ ubuntu_nvim_depends }}'
  become: yes
