- name: Add apt repositories
  apt_repository:
    repo: ppa:neovim-ppa/unstable
    update_cache: yes

- name: Install neovim by apt
  apt:
    name: '{{ item }}'
  with_items:
    - '{{ ubuntu_nvim_depends }}'

