- include_tasks: brew.yml
  when: ansible_os_family == 'Darwin'

- include_tasks: apt.yml
  when: ansible_os_family == 'Debian'

- name: Create neovim config directory
  file:
    path: "{{ nvim_config_dir }}"
    state: directory

- name: Create dein.vim cache directory
  file:
    path: "{{ nvim_cache_dir }}"
    state: directory
  loop: '{{ nvim_config_files }}'

- name: neovim config dir exists
  file:
    path: "~/{{ item | dirname }}"
    state: directory
  loop: '{{ nvim_config_files }}'

- name: Link neovim config
  file:
    src: '{{ dotfiles_repo }}/{{ item }}'
    dest: "~/{{ item }}"
    state: link
    force: yes
  loop: '{{ nvim_config_files }}'

- name: Download install script for dein.vim
  get_url:
    url: https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh
    dest: "{{ nvim_cache_dir }}/installer.sh"
  register: download_result
  until: download_result is succeeded
  retries: 3
  delay: 5

- name: Install dein.vim
  command: "bash -lc 'sh {{ nvim_cache_dir }}/installer.sh {{ nvim_cache_dir }}'"
  args:
    creates: "{{ nvim_cache_dir }}/repos/github.com/Shougo/dein.vim"
